#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
if ! pgrep mono > /dev/null
then
    export PATH=$PATH:$OPENSHIFT_DATA_DIR/mono/bin/
    export LD_LIBRARY_PATH=$OPENSHIFT_DATA_DIR/mono/lib/
    cd $OPENSHIFT_REPO_DIR/diy
    nohup mono fizteh-seabattle-gameserver.exe &
fi
